### ISSUE TITLE
rclone as cloud storage solution? 

### ISSUE THREAD

**Issue by Nornode** [ahembree/hms-docker#11]
Hey, this is awesome! 
I'm setting this up now both as intended here but also reworking some to fit a kubernetes cluster with the help of some Kompose magic. Might share that later on if anyone is interested.

Question: 
I'm using rclone as a backup solution and thinking it would be great to include that service within the containers as storage instead of relying on the local disk space for the storage-intensive parts (e.g. Media). How would you best incorporate that in this setup?

**Comment by Pr0meth3us** [comment]
I'll have to look into rclone and see what's going on. Do you know how to reference the data that's in the cloud?

I've done a lot of work to this repo to fix small bugs and change some containers around but haven't pushed the changes yet because I haven't had time to document and update everything due to a new job and other life stuff.

**Comment by Nornode** [comment]
Hey Life happens! - I appreciate the base that you have already provided! 
_thanks!_

rclone mount and you can mount cloud storage "as a normal drive" which seems to be the way the cool kids are doing it, even though it might not be best practice.
I don't know a better way myself so that probably be it.

**Comment by Pr0meth3us** [comment]
Hmmm.... it looks like rclone uses its own commands and config and stuff to mount drives, but I found [this website](https://www.jamescoyle.net/how-to/3116-rclone-systemd-startup-mount-script) where someone created a mount script that will run at startup through systemd.

**Comment by Nornode** [comment]
Yeah, that looks about right!
I haven't tried that script yet, and much less integrated it into a container... :)

**Comment by Arneby** [comment]
Hello!

Any news on this? Running the HMS containers on a VPS while saving downloaded space hogging media on my preferred cloud service would be super nice indeed.

**Comment by Pr0meth3us** [comment]
Sorry for the late response, I just noticed the additional comments and managed to look into this and it seems like a beast to configure due to all the different cloud storage providers that rclone supports. 

I might be able to integrate the rclone docker container, but I currently only have Google Drive available to test with.

Don't some cloud providers also charge for egress data? I would imagine that could get pretty costly pretty quick depending on the number of users and the quality of the media.

**Comment by Nornode** [comment]
Being a novice in some parts here, I wounder if this would do it?
https://github.com/wunderio/csi-rclone

**Comment by Pr0meth3us** [comment]
It looks like the [default rclone container](https://rclone.org/install/#install-with-docker) has the option to mount it to the host, but it requires the `SYS_ADMIN` capability and some other security stuff, and it seems like it requires rclone to already be configured on the host machine (or at least have the config file generated).

I'd imagine the mount would have to have both read/write capabilities for when new content is added so it could be uploaded to the cloud provider.

**Comment by Arneby** [comment]
> Don't some cloud providers also charge for egress data? I would imagine that could get pretty costly pretty quick 
> depending on the number of users and the quality of the media.

Yes, they do. But I don't think you need to support *all* the real cloud services but rather only the hybrid (?) ones aimed at non geek users. I'm thinking DropBox, GDrive, Box, OneDrive, Mega et c. Also, I would look at it as a single user project to begin with.

Those who really want to use AWS and the likes for this purpose most probably know how to set all this up by themselves.

**Comment by ahembree** [comment]
This project is being retired and will not receive any further updates. Please check out the new replacement project at https://github.com/ahembree/ansible-hms-docker
